#-------------------------------
# General Site Settings

baseURL = 'https://dacharycarey.com/'
languageCode = 'en-us'
title = 'Dachary Carey'
theme = 'menca'
googleAnalytics = "" # Add your identifier. For example UA-99631805-1.
paginate = 9


#-------------------------------
# Main Menu
[menu]
  [[menu.main]]
    identifier = "technical-writing"
    name = "Technical Writing"
    url = "/technical-writing"
    weight = 1

  [[menu.main]]
    identifier = "programming"
    name = "Programming"
    url = "/programming"
    weight = 2

  [[menu.main]]
    identifier = "corporate-runaways"
    name = "Corporate Runaways"
    url = "/corporate-runaways"
    weight = 3

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 4

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact"
    weight = 5


[params]
  logo = "" # You can add own logo. For example "/images/logo.png".
  description = "Menca personal blogging theme for HUGO"

  #-------------------------------
  # Author Settings
  [params.author]
    author__name = "Dachary Carey"
    author__bio = "Tech Writer, Programmer, Coffee Enthusiast"
    author__avatar = "/images/dc.jpeg"

  [[params.social]]
    icon = "ion-logo-twitter"
    name = "Mastodon"
    link = "https://mstdn.social/@dachary"

  [[params.social]]
    icon = "ion-logo-github"
    name = "GitHub"
    link = "https://github.com/dacharyc"

  [[params.social]]
    icon = "ion-logo-linkedin"
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/dachary/"

  # Example of adding a new link to the author section and footer:
  # [[params.social]]
  #   icon = "ion-logo-vimeo"
  #   name = "Vimeo"
  #   link = "https://vimeo.com"

  # Other icons can be found at https://ionicons.com/v4/


  #-------------------------------
  # Hero Settings
  [params.hero]
    hero__title = "Hey, I'm Dachary Carey"
    hero__description = "Tech Writer, Programmer, Coffee Enthusiast"
    hero__image = "/images/dc.jpeg"

  #-------------------------------
  # Gallery Footer Section
  [params.gallery]
    gallery__title = "Gallery"
    gallery__columns = 3 # You can change the number of gallery columns

  [[params.gallery_image]]
    image_alt = "Rest"
    image_url = "https://via.placeholder.com/800x600"

  [[params.gallery_image]]
    image_alt = "Lifestyle"
    image_url = "https://via.placeholder.com/800x600"

  [[params.gallery_image]]
    image_alt = "Hobby"
    image_url = "https://via.placeholder.com/800x600"

  [[params.gallery_image]]
    image_alt = "Notes"
    image_url = "https://via.placeholder.com/800x600"

  [[params.gallery_image]]
    image_alt = "Rest"
    image_url = "https://via.placeholder.com/800x600"

  [[params.gallery_image]]
    image_alt = "Hobby"
    image_url = "https://via.placeholder.com/800x600"

  [[params.gallery_image]]
    image_alt = "Fashion"
    image_url = "https://via.placeholder.com/800x600"

  [[params.gallery_image]]
    image_alt = "Notes"
    image_url = "https://via.placeholder.com/800x600"

  [[params.gallery_image]]
    image_alt = "Rest"
    image_url = "https://via.placeholder.com/800x600"


  #-------------------------------
  # Contact Settings
  [params.contact]
    email = "dc@dacharycarey.com" # Add your email for contant form

    # NOTE
    # Menca comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.

  #-------------------------------
  # Comment Section (Disqus)
  [params.disqus]
    disqusShortname = "demo-menca" # Add your shortname for Disqus Comment. For example demo-menca


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[outputs]
  home = ["HTML", "RSS", "JSON"]


[markup.highlight]
  codeFences = true
  guessSyntax = true
  noClasses = false

